class AddNewCustomer {
    constructor(
      CUSTOMER_LAST_NAME,
      CUSTOMER_FIRST_NAME,
      CUSTOMER_COMPANY_NAME,
      CUSTOMER_STREET,
      CUSTOMER_CITY,
      CUSTOMER_STATE,
      CUSTOMER_ZIPCODE,
      CUSTOMER_PRIMARY_PHONE,
      ALTERNATE_PHONE,
      WORK_PHONE,
      EXTENSION,
      ADDITIONAL_CONTACT,
      ADDITIONAL_CONTACT_PHONE,
      CUSTOMER_EMAIL,
      TAX_EXEMPT_NOTES,
      CUSTOMER_NOTES
    ) {
      this.CUSTOMER_LAST_NAME = CUSTOMER_LAST_NAME;
      this.CUSTOMER_FIRST_NAME = CUSTOMER_FIRST_NAME;
      this.CUSTOMER_COMPANY_NAME = CUSTOMER_COMPANY_NAME;
      this.CUSTOMER_STREET = CUSTOMER_STREET;
      this.CUSTOMER_CITY = CUSTOMER_CITY;
      this.CUSTOMER_STATE = CUSTOMER_STATE;
      this.CUSTOMER_ZIPCODE = CUSTOMER_ZIPCODE;
      this.CUSTOMER_PRIMARY_PHONE = CUSTOMER_PRIMARY_PHONE;
      this.ALTERNATE_PHONE = ALTERNATE_PHONE;
      this.WORK_PHONE = WORK_PHONE;
      this.EXTENSION = EXTENSION;
      this.ADDITIONAL_CONTACT = ADDITIONAL_CONTACT;
      this.ADDITIONAL_CONTACT_PHONE = ADDITIONAL_CONTACT_PHONE;
      this.CUSTOMER_EMAIL = CUSTOMER_EMAIL;
      this.TAX_EXEMPT_NOTES = TAX_EXEMPT_NOTES;
      this.CUSTOMER_NOTES = CUSTOMER_NOTES;
    }
  }

  class LookUpDataModel {
    constructor(
        CUSTOMER_LAST_NAME, CUSTOMER_FIRST_NAME, CUSTOMER_STREET, CUSTOMER_CITY, CUSTOMER_STATE,
        CUSTOMER_ZIPCODE, CUSTOMER_PRIMARY_PHONE, ALTERNATE_PHONE, CUSTOMER_EMAIL,
        MODEL, COLOR, MAKE, PRODUCTION_DATE, LICENSE_PLATE, VIN
    ) {
        this.CUSTOMER_LAST_NAME = CUSTOMER_LAST_NAME;
        this.CUSTOMER_FIRST_NAME = CUSTOMER_FIRST_NAME;
        this.CUSTOMER_STREET = CUSTOMER_STREET;
        this.CUSTOMER_CITY = CUSTOMER_CITY;
        this.CUSTOMER_STATE = CUSTOMER_STATE;
        this.CUSTOMER_ZIPCODE = CUSTOMER_ZIPCODE;
        this.CUSTOMER_PRIMARY_PHONE = CUSTOMER_PRIMARY_PHONE;
        this.ALTERNATE_PHONE = ALTERNATE_PHONE;
        this.CUSTOMER_EMAIL = CUSTOMER_EMAIL;
        this.MODEL = MODEL;
        this.COLOR = COLOR;
        this.MAKE = MAKE;
        this.PRODUCTION_DATE = PRODUCTION_DATE;
        this.LICENSE_PLATE = LICENSE_PLATE;
        this.VIN = VIN;
    }
}

  module.exports = AddNewCustomer, LookUpDataModel;
  